version: '2'
services:
  redis:
    image: redis:5-alpine
  mysql:
    image: mysql:5.6
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: gorm
  backend:
    #image: XXXXXXXXXXX.dkr.ecr.ap-southeast-1.amazonaws.com/<repo name>
    build:
      context: .
      dockerfile: Dockerfile-go
    ports:
      - "8080:8080"
    command: sh -c './wait-for redis:6379 && ./wait-for mysql:3306 -- ./web-text-manager'
    depends_on:
      - redis
